### ISSUE TITLE
Running md2orchestra from source code

### ISSUE THREAD

**Issue by nngakosso** [FIXTradingCommunity/md2spec#9]
Hello,
As you know I want to test md2spec, but I may have misunderstood how it has to be running. As stated in the README and  requirements, I've donwloaded and installed Maven and try to build from there after cloning the project on my machine.
My questions are :
-Was it the right way to proceed?
-What I understood was we modify the md2orchestra-proto.md to get an orchestra file, am I right?

I need some clarification as I'm a beginner.

Regards,

Ndakey

**Comment by donmendelson** [comment]
I will add a page in the wiki on how to build the project. In short, you need Java 11 or higher.  and Maven 3. You should be able to build all components by issuing the command `mvn install` at the root level of the project (or invoke the build from an IDE).

(Java 14 has been released. I may switch to that since it includes the jpackager utility to build native application installers.)

The project currently builds two executables: md2orchestra and orchestra2md. The README for each gives command line arguments. You can also invoke them from another Java application as a library.
 
The file md2orchestra-proto.md is a sample file that you can use for testing or as a base for modification. Other test files will be placed under folder src/test/resources.

**Comment by nngakosso** [comment]
Thank you, I just verified and it is because of my java version. I did `mvn install` several times but It always ended with an error. I got Maven 3 so everything should be fine from there.
